/* 
 * YOU MAY USE THIS SOFTWARE AND ANY DERIVATIVES EXCLUSIVELY WITH MICROCHIP
 * PRODUCTS
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, ARE PROVIDED BY MICROCHIP OR APPLY TO THIS 
 * SOFTWARE, INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, OR ITS INTERACTION 
 * WITH MICROCHIP PRODUCTS, COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN 
 * ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP  
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR THE DAMAGES ARE 
 * FORESEEABLE.  TO THE FULLEST EXTENT ALLOWED BY LAW, YOU WAIVE ANY 
 * RECOURSE AGAINST MICROCHIP WITH RESPECT TO ANY DAMAGES ARISING FROM 
 * CLAIMS IN ANY WAY RELATED TO THE SOFTWARE AND AGREE THAT ANY SUCH CLAIMS 
 * SHALL NEVER EXCEED THE AMOUNT OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY 
 * TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

#ifndef EEPROM_CONSTANTS_H
#define	EEPROM_CONSTANTS_H


/****************************TAG ADDRESS RANGES*******************************
 * VOC TAG EEPROM ADDRESS RANGE
 *      0x310000 through 0x31001F
 * 
 * REFILL TAG EEPROM ADDRESS RANGE
 *      0x31001F through 0x31003F
 * 
 * **************************************************************************/

#define VOC_EEPROM_TAG_UPPER_ADDRESS            0x31
#define VOC_EEPROM_TAG_HIGH_ADDRESS             0x00
#define VOC_EEPROM_TAG_LOW_ADDRESS              0x00
#define VOC_EEPROM_BYTE_COUNT                   32

#define REFILL_EEPROM_TAG_UPPER_ADDRESS         0x31
#define REFILL_EEPROM_TAG_HIGH_ADDRESS          0x00
#define REFILL_EEPROM_TAG_LOW_ADDRESS           0x20
#define REFILL_EEPROM_BYTE_COUNT                32


//**********************PROGRAMMED VARIABLE ADDRESS RANGES*********************
#define ADDR_EEPROM_INITIALIZED_FLAG            0x310040
#define ADDR_INTVLS_BETW_ACTIVATIONS            0x310041
#define ADDR_CABINET_LID_COUNTS_HIGH            0x310042
#define ADDR_CABINET_LID_COUNTS_LOW             0x310043
#define ADDR_DISPENSE_COUNTS_HIGH               0x310044
#define ADDR_DISPENSE_COUNTS_MID                0x310045
#define ADDR_DISPENSE_COUNTS_LOW                0x310046


//EEPROM CONSTANTS
#define EEPROM_PROGRAMMED_FLAG                  0x55



#endif	/* EEPROM_CONSTANTS_H */
